version: '2'

networks:
  app-tier:
    driver: bridge
services:
  workerserver:
    build:
      context: .
      dockerfile: workerserver/Dockerfile
    ports:
      - 50051:50051  
    networks:
      - app-tier
    links: 
      - etcd
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier