// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workerpro.proto

package workerqueue

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing
// dataTowrite
type WriteRequest struct {
	DataTowrite          string   `protobuf:"bytes,1,opt,name=dataTowrite,proto3" json:"dataTowrite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9652c55b0d8add, []int{0}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetDataTowrite() string {
	if m != nil {
		return m.DataTowrite
	}
	return ""
}

// The Write response message
type WriteResponse struct {
	Datawritten          string   `protobuf:"bytes,1,opt,name=datawritten,proto3" json:"datawritten,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9652c55b0d8add, []int{1}
}

func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (m *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(m, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetDatawritten() string {
	if m != nil {
		return m.Datawritten
	}
	return ""
}

// The request message containing
// key identifier
type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9652c55b0d8add, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// The Get response message
type GetResponse struct {
	DataResponse         string   `protobuf:"bytes,1,opt,name=dataResponse,proto3" json:"dataResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9652c55b0d8add, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetDataResponse() string {
	if m != nil {
		return m.DataResponse
	}
	return ""
}

func init() {
	proto.RegisterType((*WriteRequest)(nil), "workerqueue.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "workerqueue.WriteResponse")
	proto.RegisterType((*GetRequest)(nil), "workerqueue.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "workerqueue.GetResponse")
}

func init() {
	proto.RegisterFile("workerpro.proto", fileDescriptor_cb9652c55b0d8add)
}

var fileDescriptor_cb9652c55b0d8add = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0x84, 0x30,
	0x18, 0xc6, 0x6d, 0x4c, 0x34, 0xbc, 0x60, 0x34, 0x5d, 0x44, 0x06, 0x43, 0x3a, 0x39, 0x11, 0xd0,
	0xdd, 0xc9, 0xc8, 0x8e, 0x26, 0xcc, 0x35, 0xbe, 0xc3, 0x85, 0x84, 0x42, 0x79, 0x39, 0x72, 0x5f,
	0xe4, 0x3e, 0xef, 0xa5, 0xa5, 0xcd, 0x95, 0xdc, 0x6d, 0xf0, 0x7b, 0xfe, 0xb4, 0x4f, 0xe1, 0x71,
	0x51, 0xba, 0x43, 0x3d, 0x68, 0x55, 0x0c, 0x5a, 0x91, 0xe2, 0xf1, 0x0a, 0xc6, 0x19, 0x67, 0x14,
	0x25, 0x24, 0xad, 0xde, 0x11, 0x36, 0x38, 0xce, 0x38, 0x11, 0xcf, 0x21, 0xfe, 0x97, 0x24, 0x7f,
	0xd5, 0x62, 0x68, 0xca, 0x72, 0xf6, 0x16, 0x35, 0x21, 0x12, 0x15, 0x3c, 0xb8, 0xc4, 0x34, 0xa8,
	0x7e, 0x42, 0x1f, 0x31, 0x2a, 0x61, 0x1f, 0x46, 0x1c, 0x12, 0xaf, 0x00, 0x35, 0x92, 0x3f, 0xe2,
	0x09, 0x6e, 0x3b, 0x3c, 0x38, 0x9f, 0xf9, 0x14, 0x15, 0xc4, 0x56, 0x77, 0x85, 0x02, 0x12, 0x93,
	0xf6, 0xff, 0xce, 0xb9, 0x61, 0xef, 0x47, 0x06, 0x49, 0x6b, 0x77, 0xfc, 0xa0, 0xde, 0xa3, 0xe6,
	0xdf, 0x10, 0xd9, 0x6b, 0x7d, 0x49, 0x92, 0xfc, 0xa5, 0x08, 0x36, 0x16, 0xe1, 0xc0, 0x2c, 0xbb,
	0x26, 0xad, 0xa5, 0xe2, 0xa6, 0x64, 0xfc, 0x13, 0xee, 0x6b, 0x24, 0xdb, 0xf2, 0xbc, 0xb1, 0x9e,
	0x17, 0x64, 0xe9, 0xa5, 0xe0, 0x1b, 0xfe, 0xee, 0xec, 0x23, 0x7f, 0x9c, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0xb5, 0xba, 0xb3, 0x77, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorkerServerClient is the client API for WorkerServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerServerClient interface {
	// Sends a request to write data
	WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (WorkerServer_WriteDataClient, error)
	// Get Data written
	GetData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type workerServerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServerClient(cc grpc.ClientConnInterface) WorkerServerClient {
	return &workerServerClient{cc}
}

func (c *workerServerClient) WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (WorkerServer_WriteDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WorkerServer_serviceDesc.Streams[0], "/workerqueue.WorkerServer/WriteData", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerServerWriteDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkerServer_WriteDataClient interface {
	Recv() (*WriteResponse, error)
	grpc.ClientStream
}

type workerServerWriteDataClient struct {
	grpc.ClientStream
}

func (x *workerServerWriteDataClient) Recv() (*WriteResponse, error) {
	m := new(WriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerServerClient) GetData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/workerqueue.WorkerServer/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServerServer is the server API for WorkerServer service.
type WorkerServerServer interface {
	// Sends a request to write data
	WriteData(*WriteRequest, WorkerServer_WriteDataServer) error
	// Get Data written
	GetData(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedWorkerServerServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerServerServer struct {
}

func (*UnimplementedWorkerServerServer) WriteData(req *WriteRequest, srv WorkerServer_WriteDataServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteData not implemented")
}
func (*UnimplementedWorkerServerServer) GetData(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}

func RegisterWorkerServerServer(s *grpc.Server, srv WorkerServerServer) {
	s.RegisterService(&_WorkerServer_serviceDesc, srv)
}

func _WorkerServer_WriteData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WriteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServerServer).WriteData(m, &workerServerWriteDataServer{stream})
}

type WorkerServer_WriteDataServer interface {
	Send(*WriteResponse) error
	grpc.ServerStream
}

type workerServerWriteDataServer struct {
	grpc.ServerStream
}

func (x *workerServerWriteDataServer) Send(m *WriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkerServer_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServerServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerqueue.WorkerServer/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServerServer).GetData(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkerServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workerqueue.WorkerServer",
	HandlerType: (*WorkerServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _WorkerServer_GetData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteData",
			Handler:       _WorkerServer_WriteData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workerpro.proto",
}
